version: '3.8'

services:
  web:
    build: .
    mem_limit: 2g
    command: ["./wait-for-db.sh", "gunicorn", "mywebsite.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      -  DEBUG=True
      - DJANGO_SETTINGS_MODULE=mywebsite.settings
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

volumes:
  postgres_data:
